version: '2.3'

services:
    teach-space-invaders:
        container_name: teach-space-invaders
        image: dwoelfle/rl-notebook:0.0.5-gpu-py3
        ports: 
            - 8888:8888
        volumes: 
            - ./:/notebooks
        user: "1001:100"
        runtime: nvidia
